Upload:
  Bucket:
    default:
      AccessKeyId: xxxx
      AccessKeySecret: xxx
      Endpoint: oss-accelerate.xxxxx.com
      UrlEndpoint: xxxx.oss-accelerate.xxxx.com
      Bucket: tyut
      PathPrefix: file
    image:
      AccessKeyId: xxxx
      AccessKeySecret: xxxx
      Endpoint: oss-accelerate.xxxxx.com
      UrlEndpoint: xxxx.oss-accelerate.xxxx.com
      Bucket: tyut
      PathPrefix: image
Hexo:
  Ignore:
  - /bin
  - .git
  KeyWord:
  - xxx
  - xxx
