// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: test2.proto

package test

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestPB2Data_EnumType int32

const (
	TestPB2Data_UnknownType TestPB2Data_EnumType = 0 // 必须以0开始！
	TestPB2Data_Test1Type   TestPB2Data_EnumType = 1
	TestPB2Data_Test2Type   TestPB2Data_EnumType = 2
)

// Enum value maps for TestPB2Data_EnumType.
var (
	TestPB2Data_EnumType_name = map[int32]string{
		0: "UnknownType",
		1: "Test1Type",
		2: "Test2Type",
	}
	TestPB2Data_EnumType_value = map[string]int32{
		"UnknownType": 0,
		"Test1Type":   1,
		"Test2Type":   2,
	}
)

func (x TestPB2Data_EnumType) Enum() *TestPB2Data_EnumType {
	p := new(TestPB2Data_EnumType)
	*p = x
	return p
}

func (x TestPB2Data_EnumType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TestPB2Data_EnumType) Descriptor() protoreflect.EnumDescriptor {
	return file_test2_proto_enumTypes[0].Descriptor()
}

func (TestPB2Data_EnumType) Type() protoreflect.EnumType {
	return &file_test2_proto_enumTypes[0]
}

func (x TestPB2Data_EnumType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *TestPB2Data_EnumType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = TestPB2Data_EnumType(num)
	return nil
}

// Deprecated: Use TestPB2Data_EnumType.Descriptor instead.
func (TestPB2Data_EnumType) EnumDescriptor() ([]byte, []int) {
	return file_test2_proto_rawDescGZIP(), []int{0, 0}
}

type TestPB2Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TString     *string                   `protobuf:"bytes,1,opt,name=t_string,json=tString" json:"t_string,omitempty"`
	TInt64      *int64                    `protobuf:"varint,2,opt,name=t_int64,json=tInt64" json:"t_int64,omitempty"`
	TBool       *bool                     `protobuf:"varint,3,req,name=t_bool,json=tBool" json:"t_bool,omitempty"`
	TFix64      *uint64                   `protobuf:"fixed64,4,req,name=t_fix64,json=tFix64" json:"t_fix64,omitempty"`
	TListI64    []int64                   `protobuf:"varint,5,rep,packed,name=t_list_i64,json=tListI64" json:"t_list_i64,omitempty"`
	TMap        map[int64]string          `protobuf:"bytes,6,rep,name=t_map,json=tMap" json:"t_map,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TEnum       *TestPB2Data_EnumType     `protobuf:"varint,7,opt,name=t_enum,json=tEnum,enum=TestPB2Data_EnumType" json:"t_enum,omitempty"`
	TObj        *TestPB2Data_TestPB2Obj   `protobuf:"bytes,8,opt,name=t_obj,json=tObj" json:"t_obj,omitempty"`
	TListObj    []*TestPB2Data_TestPB2Obj `protobuf:"bytes,9,rep,name=t_list_obj,json=tListObj" json:"t_list_obj,omitempty"`
	TMapObj     map[string]*TestPB2Data   `protobuf:"bytes,10,rep,name=t_map_obj,json=tMapObj" json:"t_map_obj,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TListString []string                  `protobuf:"bytes,11,rep,name=t_list_string,json=tListString" json:"t_list_string,omitempty"`
	Any         *anypb.Any                `protobuf:"bytes,12,opt,name=any" json:"any,omitempty"`
	Result      []*TestPB2Data_Result     `protobuf:"group,13,rep,name=Result,json=result" json:"result,omitempty"`
	TDouble     *float64                  `protobuf:"fixed64,14,opt,name=t_double,json=tDouble" json:"t_double,omitempty"`
	TBytes      []byte                    `protobuf:"bytes,15,opt,name=t_bytes,json=tBytes" json:"t_bytes,omitempty"`
}

func (x *TestPB2Data) Reset() {
	*x = TestPB2Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test2_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestPB2Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestPB2Data) ProtoMessage() {}

func (x *TestPB2Data) ProtoReflect() protoreflect.Message {
	mi := &file_test2_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestPB2Data.ProtoReflect.Descriptor instead.
func (*TestPB2Data) Descriptor() ([]byte, []int) {
	return file_test2_proto_rawDescGZIP(), []int{0}
}

func (x *TestPB2Data) GetTString() string {
	if x != nil && x.TString != nil {
		return *x.TString
	}
	return ""
}

func (x *TestPB2Data) GetTInt64() int64 {
	if x != nil && x.TInt64 != nil {
		return *x.TInt64
	}
	return 0
}

func (x *TestPB2Data) GetTBool() bool {
	if x != nil && x.TBool != nil {
		return *x.TBool
	}
	return false
}

func (x *TestPB2Data) GetTFix64() uint64 {
	if x != nil && x.TFix64 != nil {
		return *x.TFix64
	}
	return 0
}

func (x *TestPB2Data) GetTListI64() []int64 {
	if x != nil {
		return x.TListI64
	}
	return nil
}

func (x *TestPB2Data) GetTMap() map[int64]string {
	if x != nil {
		return x.TMap
	}
	return nil
}

func (x *TestPB2Data) GetTEnum() TestPB2Data_EnumType {
	if x != nil && x.TEnum != nil {
		return *x.TEnum
	}
	return TestPB2Data_UnknownType
}

func (x *TestPB2Data) GetTObj() *TestPB2Data_TestPB2Obj {
	if x != nil {
		return x.TObj
	}
	return nil
}

func (x *TestPB2Data) GetTListObj() []*TestPB2Data_TestPB2Obj {
	if x != nil {
		return x.TListObj
	}
	return nil
}

func (x *TestPB2Data) GetTMapObj() map[string]*TestPB2Data {
	if x != nil {
		return x.TMapObj
	}
	return nil
}

func (x *TestPB2Data) GetTListString() []string {
	if x != nil {
		return x.TListString
	}
	return nil
}

func (x *TestPB2Data) GetAny() *anypb.Any {
	if x != nil {
		return x.Any
	}
	return nil
}

func (x *TestPB2Data) GetResult() []*TestPB2Data_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *TestPB2Data) GetTDouble() float64 {
	if x != nil && x.TDouble != nil {
		return *x.TDouble
	}
	return 0
}

func (x *TestPB2Data) GetTBytes() []byte {
	if x != nil {
		return x.TBytes
	}
	return nil
}

type TestAnyTypePB2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Any *anypb.Any `protobuf:"bytes,1,opt,name=any" json:"any,omitempty"`
}

func (x *TestAnyTypePB2) Reset() {
	*x = TestAnyTypePB2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test2_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestAnyTypePB2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestAnyTypePB2) ProtoMessage() {}

func (x *TestAnyTypePB2) ProtoReflect() protoreflect.Message {
	mi := &file_test2_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestAnyTypePB2.ProtoReflect.Descriptor instead.
func (*TestAnyTypePB2) Descriptor() ([]byte, []int) {
	return file_test2_proto_rawDescGZIP(), []int{1}
}

func (x *TestAnyTypePB2) GetAny() *anypb.Any {
	if x != nil {
		return x.Any
	}
	return nil
}

type Type1PB2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value *string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (x *Type1PB2) Reset() {
	*x = Type1PB2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test2_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Type1PB2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Type1PB2) ProtoMessage() {}

func (x *Type1PB2) ProtoReflect() protoreflect.Message {
	mi := &file_test2_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Type1PB2.ProtoReflect.Descriptor instead.
func (*Type1PB2) Descriptor() ([]byte, []int) {
	return file_test2_proto_rawDescGZIP(), []int{2}
}

func (x *Type1PB2) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

type Type2PB2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value *int64 `protobuf:"varint,1,opt,name=value" json:"value,omitempty"`
}

func (x *Type2PB2) Reset() {
	*x = Type2PB2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test2_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Type2PB2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Type2PB2) ProtoMessage() {}

func (x *Type2PB2) ProtoReflect() protoreflect.Message {
	mi := &file_test2_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Type2PB2.ProtoReflect.Descriptor instead.
func (*Type2PB2) Descriptor() ([]byte, []int) {
	return file_test2_proto_rawDescGZIP(), []int{3}
}

func (x *Type2PB2) GetValue() int64 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

type Type3PB2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value *float32 `protobuf:"fixed32,1,opt,name=value" json:"value,omitempty"`
}

func (x *Type3PB2) Reset() {
	*x = Type3PB2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test2_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Type3PB2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Type3PB2) ProtoMessage() {}

func (x *Type3PB2) ProtoReflect() protoreflect.Message {
	mi := &file_test2_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Type3PB2.ProtoReflect.Descriptor instead.
func (*Type3PB2) Descriptor() ([]byte, []int) {
	return file_test2_proto_rawDescGZIP(), []int{4}
}

func (x *Type3PB2) GetValue() float32 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

type Type4PB2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []string `protobuf:"bytes,1,rep,name=value" json:"value,omitempty"`
}

func (x *Type4PB2) Reset() {
	*x = Type4PB2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test2_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Type4PB2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Type4PB2) ProtoMessage() {}

func (x *Type4PB2) ProtoReflect() protoreflect.Message {
	mi := &file_test2_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Type4PB2.ProtoReflect.Descriptor instead.
func (*Type4PB2) Descriptor() ([]byte, []int) {
	return file_test2_proto_rawDescGZIP(), []int{5}
}

func (x *Type4PB2) GetValue() []string {
	if x != nil {
		return x.Value
	}
	return nil
}

type TestPB2Data_TestPB2Obj struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TInt64 *int64 `protobuf:"varint,1,opt,name=t_int64,json=tInt64" json:"t_int64,omitempty"`
}

func (x *TestPB2Data_TestPB2Obj) Reset() {
	*x = TestPB2Data_TestPB2Obj{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test2_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestPB2Data_TestPB2Obj) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestPB2Data_TestPB2Obj) ProtoMessage() {}

func (x *TestPB2Data_TestPB2Obj) ProtoReflect() protoreflect.Message {
	mi := &file_test2_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestPB2Data_TestPB2Obj.ProtoReflect.Descriptor instead.
func (*TestPB2Data_TestPB2Obj) Descriptor() ([]byte, []int) {
	return file_test2_proto_rawDescGZIP(), []int{0, 0}
}

func (x *TestPB2Data_TestPB2Obj) GetTInt64() int64 {
	if x != nil && x.TInt64 != nil {
		return *x.TInt64
	}
	return 0
}

type TestPB2Data_Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url      *string  `protobuf:"bytes,2,req,name=url" json:"url,omitempty"`
	Title    *string  `protobuf:"bytes,3,opt,name=title" json:"title,omitempty"`
	Snippets []string `protobuf:"bytes,4,rep,name=snippets" json:"snippets,omitempty"`
}

func (x *TestPB2Data_Result) Reset() {
	*x = TestPB2Data_Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test2_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestPB2Data_Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestPB2Data_Result) ProtoMessage() {}

func (x *TestPB2Data_Result) ProtoReflect() protoreflect.Message {
	mi := &file_test2_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestPB2Data_Result.ProtoReflect.Descriptor instead.
func (*TestPB2Data_Result) Descriptor() ([]byte, []int) {
	return file_test2_proto_rawDescGZIP(), []int{0, 3}
}

func (x *TestPB2Data_Result) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

func (x *TestPB2Data_Result) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *TestPB2Data_Result) GetSnippets() []string {
	if x != nil {
		return x.Snippets
	}
	return nil
}

var File_test2_proto protoreflect.FileDescriptor

var file_test2_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x74, 0x65, 0x73, 0x74, 0x32, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61,
	0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xea, 0x06, 0x0a, 0x0b, 0x54, 0x65, 0x73,
	0x74, 0x50, 0x42, 0x32, 0x44, 0x61, 0x74, 0x61, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x5f, 0x73, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x5f, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x74, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x12, 0x15, 0x0a, 0x06,
	0x74, 0x5f, 0x62, 0x6f, 0x6f, 0x6c, 0x18, 0x03, 0x20, 0x02, 0x28, 0x08, 0x52, 0x05, 0x74, 0x42,
	0x6f, 0x6f, 0x6c, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x5f, 0x66, 0x69, 0x78, 0x36, 0x34, 0x18, 0x04,
	0x20, 0x02, 0x28, 0x06, 0x52, 0x06, 0x74, 0x46, 0x69, 0x78, 0x36, 0x34, 0x12, 0x20, 0x0a, 0x0a,
	0x74, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x69, 0x36, 0x34, 0x18, 0x05, 0x20, 0x03, 0x28, 0x03,
	0x42, 0x02, 0x10, 0x01, 0x52, 0x08, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x36, 0x34, 0x12, 0x2b,
	0x0a, 0x05, 0x74, 0x5f, 0x6d, 0x61, 0x70, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x54, 0x65, 0x73, 0x74, 0x50, 0x42, 0x32, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x54, 0x4d, 0x61, 0x70,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x74, 0x4d, 0x61, 0x70, 0x12, 0x2c, 0x0a, 0x06, 0x74,
	0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x54, 0x65,
	0x73, 0x74, 0x50, 0x42, 0x32, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x05, 0x74, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x2c, 0x0a, 0x05, 0x74, 0x5f, 0x6f,
	0x62, 0x6a, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x50,
	0x42, 0x32, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x50, 0x42, 0x32, 0x4f, 0x62,
	0x6a, 0x52, 0x04, 0x74, 0x4f, 0x62, 0x6a, 0x12, 0x35, 0x0a, 0x0a, 0x74, 0x5f, 0x6c, 0x69, 0x73,
	0x74, 0x5f, 0x6f, 0x62, 0x6a, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x54, 0x65,
	0x73, 0x74, 0x50, 0x42, 0x32, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x50, 0x42,
	0x32, 0x4f, 0x62, 0x6a, 0x52, 0x08, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x62, 0x6a, 0x12, 0x35,
	0x0a, 0x09, 0x74, 0x5f, 0x6d, 0x61, 0x70, 0x5f, 0x6f, 0x62, 0x6a, 0x18, 0x0a, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x50, 0x42, 0x32, 0x44, 0x61, 0x74, 0x61, 0x2e,
	0x54, 0x4d, 0x61, 0x70, 0x4f, 0x62, 0x6a, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x74, 0x4d,
	0x61, 0x70, 0x4f, 0x62, 0x6a, 0x12, 0x22, 0x0a, 0x0d, 0x74, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x5f,
	0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x4c,
	0x69, 0x73, 0x74, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x26, 0x0a, 0x03, 0x61, 0x6e, 0x79,
	0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x03, 0x61, 0x6e,
	0x79, 0x12, 0x2b, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x0d, 0x20, 0x03, 0x28,
	0x0a, 0x32, 0x13, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x50, 0x42, 0x32, 0x44, 0x61, 0x74, 0x61, 0x2e,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x19,
	0x0a, 0x08, 0x74, 0x5f, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x07, 0x74, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x5f, 0x62,
	0x79, 0x74, 0x65, 0x73, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x74, 0x42, 0x79, 0x74,
	0x65, 0x73, 0x1a, 0x25, 0x0a, 0x0a, 0x54, 0x65, 0x73, 0x74, 0x50, 0x42, 0x32, 0x4f, 0x62, 0x6a,
	0x12, 0x17, 0x0a, 0x07, 0x74, 0x5f, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x74, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x1a, 0x37, 0x0a, 0x09, 0x54, 0x4d, 0x61,
	0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02,
	0x38, 0x01, 0x1a, 0x48, 0x0a, 0x0c, 0x54, 0x4d, 0x61, 0x70, 0x4f, 0x62, 0x6a, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x22, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x50, 0x42, 0x32, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x4c, 0x0a, 0x06,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20,
	0x02, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x73, 0x6e, 0x69, 0x70, 0x70, 0x65, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x08, 0x73, 0x6e, 0x69, 0x70, 0x70, 0x65, 0x74, 0x73, 0x22, 0x39, 0x0a, 0x08, 0x45, 0x6e,
	0x75, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x54, 0x65, 0x73, 0x74, 0x31,
	0x54, 0x79, 0x70, 0x65, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x54, 0x65, 0x73, 0x74, 0x32, 0x54,
	0x79, 0x70, 0x65, 0x10, 0x02, 0x22, 0x38, 0x0a, 0x0e, 0x54, 0x65, 0x73, 0x74, 0x41, 0x6e, 0x79,
	0x54, 0x79, 0x70, 0x65, 0x50, 0x42, 0x32, 0x12, 0x26, 0x0a, 0x03, 0x61, 0x6e, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x03, 0x61, 0x6e, 0x79, 0x22,
	0x20, 0x0a, 0x08, 0x54, 0x79, 0x70, 0x65, 0x31, 0x50, 0x42, 0x32, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x22, 0x20, 0x0a, 0x08, 0x54, 0x79, 0x70, 0x65, 0x32, 0x50, 0x42, 0x32, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x22, 0x20, 0x0a, 0x08, 0x54, 0x79, 0x70, 0x65, 0x33, 0x50, 0x42, 0x32, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x20, 0x0a, 0x08, 0x54, 0x79, 0x70, 0x65, 0x34, 0x50, 0x42,
	0x32, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
}

var (
	file_test2_proto_rawDescOnce sync.Once
	file_test2_proto_rawDescData = file_test2_proto_rawDesc
)

func file_test2_proto_rawDescGZIP() []byte {
	file_test2_proto_rawDescOnce.Do(func() {
		file_test2_proto_rawDescData = protoimpl.X.CompressGZIP(file_test2_proto_rawDescData)
	})
	return file_test2_proto_rawDescData
}

var file_test2_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_test2_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_test2_proto_goTypes = []interface{}{
	(TestPB2Data_EnumType)(0),      // 0: TestPB2Data.EnumType
	(*TestPB2Data)(nil),            // 1: TestPB2Data
	(*TestAnyTypePB2)(nil),         // 2: TestAnyTypePB2
	(*Type1PB2)(nil),               // 3: Type1PB2
	(*Type2PB2)(nil),               // 4: Type2PB2
	(*Type3PB2)(nil),               // 5: Type3PB2
	(*Type4PB2)(nil),               // 6: Type4PB2
	(*TestPB2Data_TestPB2Obj)(nil), // 7: TestPB2Data.TestPB2Obj
	nil,                            // 8: TestPB2Data.TMapEntry
	nil,                            // 9: TestPB2Data.TMapObjEntry
	(*TestPB2Data_Result)(nil),     // 10: TestPB2Data.Result
	(*anypb.Any)(nil),              // 11: google.protobuf.Any
}
var file_test2_proto_depIdxs = []int32{
	8,  // 0: TestPB2Data.t_map:type_name -> TestPB2Data.TMapEntry
	0,  // 1: TestPB2Data.t_enum:type_name -> TestPB2Data.EnumType
	7,  // 2: TestPB2Data.t_obj:type_name -> TestPB2Data.TestPB2Obj
	7,  // 3: TestPB2Data.t_list_obj:type_name -> TestPB2Data.TestPB2Obj
	9,  // 4: TestPB2Data.t_map_obj:type_name -> TestPB2Data.TMapObjEntry
	11, // 5: TestPB2Data.any:type_name -> google.protobuf.Any
	10, // 6: TestPB2Data.result:type_name -> TestPB2Data.Result
	11, // 7: TestAnyTypePB2.any:type_name -> google.protobuf.Any
	1,  // 8: TestPB2Data.TMapObjEntry.value:type_name -> TestPB2Data
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_test2_proto_init() }
func file_test2_proto_init() {
	if File_test2_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_test2_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestPB2Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test2_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestAnyTypePB2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test2_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Type1PB2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test2_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Type2PB2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test2_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Type3PB2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test2_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Type4PB2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test2_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestPB2Data_TestPB2Obj); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test2_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestPB2Data_Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_test2_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_test2_proto_goTypes,
		DependencyIndexes: file_test2_proto_depIdxs,
		EnumInfos:         file_test2_proto_enumTypes,
		MessageInfos:      file_test2_proto_msgTypes,
	}.Build()
	File_test2_proto = out.File
	file_test2_proto_rawDesc = nil
	file_test2_proto_goTypes = nil
	file_test2_proto_depIdxs = nil
}
