name: Pull Request Check

on: [ pull_request ]

jobs:
  checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.13.15'
      - name: Apt Install ...
        run: sudo apt-get update; sudo apt-get install libpcap-dev
      - name: Show Project ...
        run: ls -al
      - name: CI
        run: make ci
      - name: Golangci Lint
        # https://golangci-lint.run/
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest