name: Pull Request Check

on: [ pull_request ]

jobs:
  checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.13.15'
      - name: Apt Install ...
        run: sudo apt-get update; sudo apt-get install libpcap-dev
      - name: Show Project ...
        run: ls -al
      - name: CI
        run: make ci
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.41.1